server:
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8

    accept-count: 200

    min-spare-threads: 10

    max-connections: 20000

    max-threads: 500
  address: 0.0.0.0
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev




